export const GET_WEATHER_PENDING = "GET_WEATHER_PENDING";
export const GET_WEATHER_RESOLVED = "GET_WEATHER_RESOLVED";
export const GET_WEATHER_REJECTED = "GET_WEATHER_REJECTED";
export const GET_WEATHER_FIVE_DAYS_PENDING = "GET_WEATHER_FIVE_DAYS_PENDING";
export const GET_WEATHER_FIVE_DAYS_RESOLVED = "GET_WEATHER_FIVE_DAYS_RESOLVED";
export const GET_WEATHER_FIVE_DAYS_REJECTED = "GET_WEATHER_FIVE_DAYS_REJECTED";
